repos:
  # Autoformat: YAML, JSON, Markdown, etc.
  - repo: https://github.com/pycontribs/mirrors-prettier
    rev: v3.3.3
    hooks:
      - id: prettier
        args: [--ignore-unknown, --no-error-on-unmatched-pattern, "!LICENSE.md"]

  # Lint: Markdown
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint
        args: [--fix, --ignore, CHANGELOG.md, --ignore, LICENSE.md]
