name: 🔧 Build MKDocs Image

on:
  workflow_dispatch:

jobs:
  build-odkcentral:
    uses: hotosm/gh-workflows/.github/workflows/image_build.yml@1.0.1
    with:
      image_name: ghcr.io/${{ github.repository }}/mkdocs
      dockerfile: images/mkdocs/Dockerfile
