name: Build Doxygen

on:
  workflow_call:
    inputs:
      output_path:
        description: "If specified, the output dir is uploaded named `artifact`."
        required: false
        type: string
    outputs:
      artifact_name:
        description: "The artifact name (default: `artifact`)."
        value: "doxygen"

jobs:
  build_doxygen:
    name: Build Doxygen Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz --no-install-recommends

      - name: Build Doxygen Docs
        working-directory: docs
        run: doxygen

      # TODO check if this is required since upload-artifact v4
      # - name: Zip Artifact Dir
      #   if: ${{ inputs.output_path }}
      #   run: |
      #     tar -cvzf doxygen.tar.gz ${{ inputs.output_path }}

      - name: Upload Artifact Dir
        if: ${{ inputs.output_path }}
        uses: actions/upload-artifact@v4
        with:
          path: ${{ inputs.output_path }}
          name: doxygen
