name: Build Doxygen

on:
  workflow_call:
    inputs:
      cache_paths:
        description: "The paths to cache for preceeding/following jobs."
        required: false
        type: string
      cache_key:
        description: "The cache key to receive from a previous job."
        required: false
        type: string

jobs:
  build_doxygen:
    name: Build Doxygen Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen

      - name: Write cache
        if: ${{ inputs.cache_key != '' }}
        uses: actions/cache@v3
        with:
          path: |
            .cache
            ${{ inputs.cache_paths }}
          key: ${{ inputs.cache_key }}

      - name: Build Doxygen Docs
        run: |
          cd docs
          doxygen
