name: Cache Container Images

on:
  workflow_call:
    inputs:
      image_names:
        description: "A space separated list of full image names to cache, including tag."
        required: true
        type: string
      cache_key:
        description: "The cache key to use, e.g. image-cache."
        required: true
        type: string
    outputs:
      cache_key:
        description: "The cache key used during input."
        value: ${{ inputs.cache_key }}

jobs:
  package-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Package Images
        run: |
          # Remove leading and trailing whitespace and empty lines
          input_vars=$(echo -e "${{ inputs.image_names }}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' -e '/^$/d')
          # Split the space-separated string into an array
          IFS=$'\n' read -ra image_names_array <<< "$input_vars"
          echo "Parsed array: ${image_names_array}"

          # Make artifact dir
          mkdir -p /tmp/images

          # Iterate images
          for image_name in "${image_names_array[@]}"; do
              docker pull "${image_name}"
              img_underscores=${image_name//[:\/]/_}
              echo "Packaging image to /tmp/images/${img_underscores}.tar"
              docker image save "${image_name}" \
                --output /tmp/images/${img_underscores}.tar
          done

      - name: Upload Artifact Dir
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.cache_key }}
          path: /tmp/images
