name: Cache Container Images

on:
  workflow_call:
    inputs:
      image_names:
        description: "A space separated list of full image names to cache, including tag."
        required: true
        type: string
      artifact_name:
        description: "The cache key to use, e.g. image-cache."
        required: true
        type: string
    outputs:
      artifact_name:
        description: "The cache key used during input."
        value: ${{ inputs.artifact_name }}

jobs:
  package-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Package Images
        run: |
          echo "Provided images:"
          echo "${{ inputs.image_names }}"
          {
            echo 'IMAGES<<EOF'
            "${{ inputs.image_names }}"
            echo EOF
          } >> "$GITHUB_ENV"
          echo "Parsed to GITHUB_ENV:"
          echo "${IMAGES}"

          # Split the space-separated string into an array
          IFS=$'\n' read -ra images_array <<< "$IMAGES"
          echo "Parsed array:"
          "${images_array[@]}"

          # Make artifact dir
          mkdir -p /tmp/images

          # Iterate images
          for image_name in "${images_array[@]}"; do
              docker pull "${image_name}"
              img_underscores=${image_name//[:\/]/_}
              echo "Packaging image to /tmp/images/${img_underscores}.tar"
              docker image save "${image_name}" \
                --output /tmp/images/${img_underscores}.tar
          done

      - name: Upload Artifact Dir
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact_name }}
          path: /tmp/images
