name: Artifact Container Images

on:
  workflow_call:
    inputs:
      image_names:
        description: "A space separated list of full image names to upload, including tag."
        required: true
        type: string
    outputs:
      artifact_name:
        description: "The artifact name (default: `artifact`)."
        value: "artifact"

jobs:
  package-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Package Images
        run: |
          # Make artifact dir
          mkdir -p /tmp/images

          echo "Provided images:"
          echo "${{ inputs.image_names }}"
          echo ""

          images_array=(${{ inputs.image_names }})
          echo "Parsed array: ${images_array}"
          echo "Images to artifact:"
          for image in "${images_array[@]}"; do
            echo "$image"
          done
          echo ""

          # Iterate images
          for image in "${images_array[@]}"; do
              echo "Processing image ${image}"
              docker pull "${image}"

              if [ $? -eq 0 ]; then
                  img_underscores=${image//[:\/.]/_}
                  echo "Packaging image to /tmp/images/${img_underscores}.tar"
                  docker image save "${image}" \
                      --output /tmp/images/${img_underscores}.tar
              else
                  echo "Failed to pull the image: ${image}"
              fi
          done

      - name: Upload Artifact Dir
        uses: actions/upload-artifact@v4
        with:
          path: /tmp/images
          key: images
