name: Cache Container Image

on:
  workflow_call:
    inputs:
      image_name:
        description: "The full image name to cache, including tag."
        required: true
        type: string
      cache_key:
        description: "The cache key to use, e.g. img-postgis."
        required: true
        type: string
    outputs:
      cache_key:
        description: "The cache key used during input."
        value: ${{ inputs.cache_key }}

jobs:
  cache-img:
    runs-on: ubuntu-latest
    steps:
      - name: Check Img Artifact Exists
        id: check-artifact
        uses: xSAVIKx/artifact-exists-action@v0
        with:
          name: ${{ inputs.cache_key }}

      - name: Package Image
        if: steps.check-artifact.outputs.exists != true
        run: |
          docker pull ${{ inputs.image_name }}
          docker image save ${{ inputs.image_name }} \
            --output /tmp/${{ inputs.cache_key }}.tar

      - name: Upload Artifact
        if: steps.check-artifact.outputs.exists != true
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.cache_key }}
          path: /tmp/${{ inputs.cache_key }}.tar
