name: Cache Container Images

on:
  workflow_call:
    inputs:
      image_names:
        description: "A space separated list of full image names to cache, including tag."
        required: true
        type: string
      cache_key:
        description: "The cache key to use, e.g. image-cache."
        required: true
        type: string
    outputs:
      cache_key:
        description: "The cache key used during input."
        value: ${{ inputs.cache_key }}

jobs:
  cache-imgs:
    runs-on: ubuntu-latest
    steps:
      - name: Package Images
        run: |
          mkdir -p /tmp/images
          for image_name in "${{ inputs.image_names }}"; do
              docker pull "${image_name}"
              img_underscores=${image_name//\//\_}
              echo "Packaging image to /tmp/${img_underscores}.tar"
              docker image save "${image_name}" \
                --output /tmp/${img_underscores}.tar
          done

      - name: Upload Artifact Dir
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.cache_key }}
          path: /tmp/images
