name: Container Image Build

on:
  workflow_call:
    inputs:
      image_name:
        description: "Name of image, without tags."
        required: true
        type: string
      image_tags:
        description: "Default=the images are automatically tagged. Override tags with space separated list."
        required: false
        type: string
        default: ""
      build_args:
        description: "Space separated list of build args to use for the image."
        required: false
        type: string
      registry:
        description: "Override GHCR to use an external reg."
        required: false
        type: string
        default: "ghcr.io"
      context:
        description: "Root directory to start the build from."
        required: false
        type: string
        default: "."
      dockerfile:
        description: "Absolute path of the dockerfile (inside the context dir)."
        required: false
        type: string
        default: "Dockerfile"
      build_target:
        description: "The target to built to (default to end of the Dockerfile)."
        required: false
        type: string
        default: ""
      push:
        description: "Override prevent pushing the image."
        required: false
        type: boolean
        default: true
      cache:
        description: "Use GHCR caching. Default true. Set this false if registry is not ghcr.io."
        required: false
        type: boolean
        default: true
      multi_arch:
        description: "Build a multi-arch image for AMD/ARM."
        required: false
        type: boolean
        default: true

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Scan Dockerfile Vulnerabilities
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ${{ inputs.context }}
          framework: dockerfile # only ask for dockerfile scans
          quiet: true # show only failed checks
          container_user: 1001 # UID to run the container under for permissions

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Image Tags
        if: inputs.image_tags == ''
        id: set-tags
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.image_name }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Set up QEMU
        if: inputs.multi_arch == 'true'
        uses: docker/setup-qemu-action@v2

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.context }}/${{ inputs.dockerfile }}
          target: ${{ inputs.build_target }}
          push: ${{ inputs.push }}
          tags: ${{ inputs.image_tags | steps.set-tags.outputs.tags }}
          build-args: ${{ inputs.build_args }}
          cache-from: ${{ inputs.cache == 'true' && 'type=gha' || '' }}
          cache-to: ${{ inputs.cache == 'true' && 'type=gha,mode=max' || '' }}
          # Build for AMD and ARM (requires buildx+qemu)
          platforms: ${{ inputs.multi_arch == 'true' && 'linux/amd64,linux/arm64' || 'linux/amd64' }}
