name: Container Image Build

on:
  workflow_call:
    inputs:
      image_tags:
        description: "Space separated list of tags for the built image."
        required: true
        type: string
      build_args:
        description: "Space separated list of build args to use for the image."
        required: true
        type: string
      registry:
        description: "Override GHCR to use an external reg."
        required: false
        type: string
        default: "ghcr.io"
      context:
        description: "Root directory to start the build from."
        required: false
        type: string
        default: "${{ inputs.context }}/Dockerfile"
      dockerfile:
        description: "Absolute path of the dockerfile (inside the context dir)."
        required: false
        type: string
        default: "Dockerfile"
      build_target:
        description: "The target to built to (default to end of the Dockerfile)."
        required: false
        type: string
        default: ""
      push:
        description: "Override prevent pushing the image."
        required: false
        type: boolean
        default: true

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          target: ${{ inputs.build_target }}
          push: ${{ inputs.push }}
          tags: ${{ inputs.image_tags }}
          build-args: ${{ inputs.build_args }}
