name: Cache Container Image

on:
  workflow_call:
    inputs:
      image_name:
        description: "The full image name to cache, including tag."
        required: true
        type: string
      cache_key:
        description: "The cache key to use, e.g. img-postgis."
        required: true
        type: string
    outputs:
      cache_key:
        description: "The cache key used during input."
        value: ${{ inputs.cache_key }}
      cache_path:
        description: "The path that was cached."
        value: ci/cache/images/${{ inputs.cache_key }}.tar

jobs:
  cache-image:
    runs-on: ubuntu-latest

    steps:
      - name: Set Img Cache
        id: cache-img
        uses: actions/cache@v3
        with:
          path: ci/cache/images/${{ inputs.cache_key }}.tar
          key: ${{ inputs.cache_key }}

      - name: Update Img Cache
        if: steps.cache-img.outputs.cache-hit != 'true'
        run: |
          docker pull ${{ inputs.image_name }}
          mkdir -p ci/cache/images
          docker image save ${{ inputs.image_name }} \
            --output ./ci/cache/images/${{ inputs.cache_key }}.tar
