name: Cache Container Image

on:
  workflow_call:
    inputs:
      registry_prefix:
        description: "The registry prefix, e.g. ghcr.io/hotosm."
        required: false
        type: string
        default: "docker.io"
      image_name:
        description: "The image name to cache, with tag, e.g. fmtm:0.1.0."
        required: true
        type: string

jobs:
  cache-image:
    runs-on: ubuntu-latest
    steps:
      - name: Restore Image Cache
        id: cache-img
        uses: actions/cache@v3
        with:
          path: ci/cache/images/${{ inputs.image_name }}.tar
          key: cache-docker-${{ inputs.image_name }}

      - name: Update Image Cache
        if: steps.cache-img.outputs.cache-hit != 'true'
        run: |
          docker pull ${{ inputs.registry_prefix }}/${{ inputs.image_name }}
          mkdir -p ci/cache/images
          docker image save ${{ inputs.registry_prefix }}/${{ inputs.image_name }} \
            --output ./ci/cache/images/${{ inputs.image_name }}.tar

      - name: Use Image Cache
        if: steps.cache-img.outputs.cache-hit == 'true'
        run: docker image load --input ./ci/cache/images/${{ inputs.image_name }}.tar
