name: Cache Container Images

on:
  workflow_call:
    inputs:
      image_names:
        description: "A space separated list of full image names to cache, including tag."
        required: true
        type: string
      cache_key:
        description: "The cache key to use, e.g. image-cache."
        required: true
        type: string
    outputs:
      cache_key:
        description: "The cache key used during input."
        value: ${{ inputs.cache_key }}

jobs:
  package-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Package Images
        run: |
          echo "Provided images:"
          echo "${{ inputs.image_names }}"

          # Split the space-separated string into an array
          image_names_array=()
          while IFS= read -r line; do
            image_names_array+=("$line")
          done <<< "${{ inputs.image_names }}"

          echo ""
          echo "Parsed array:"
          "${image_names_array[@]}"
          echo ""

          # Make artifact dir
          mkdir -p /tmp/images

          # Iterate images
          for image_name in "${image_names_array[@]}"; do
              docker pull "${image_name}"
              img_underscores=${image_name//[:\/]/_}
              echo "Packaging image to /tmp/images/${img_underscores}.tar"
              docker image save "${image_name}" \
                --output /tmp/images/${img_underscores}.tar
          done

      - name: Upload Artifact Dir
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.cache_key }}
          path: /tmp/images
