name: Publish Docs

on:
  workflow_call:
    inputs:
      image:
        description: "Override the image to build mkdocs."
        required: false
        type: string
        default: "docker.io/squidfunk/mkdocs-material:9"
      cache_paths:
        description: "The paths to cache for preceeding/following jobs."
        required: false
        type: string
      cache_key:
        description: "The cache key to receive from a previous job."
        required: false
        type: string
      prepend_command:
        description: "Command to run before mkdocs deploy (e.g. 'gosu appuser' to run as appuser)."
        required: false
        type: string
        default: ""

permissions:
  contents: write

jobs:
  publish_docs:
    name: Publish GH Pages
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read cache
        uses: actions/cache@v3
        with:
          path: |
            .cache
            ${{ inputs.cache_paths }}
          key: ${{ inputs.cache_key }}
          restore-keys: ${{ inputs.cache_key }}

      - name: Publish
        run: |
          chmod -R 777 .
          ${{ inputs.prepend_command }} mkdocs gh-deploy --force
