name: Publish Docs

on:
  workflow_call:
    inputs:
      image:
        description: "Override the image to build mkdocs."
        required: false
        type: string
        default: "docker.io/squidfunk/mkdocs-material:9"
      doxygen:
        description: "Include doxygen output uploaded to extra-docs-files artifact."
        required: false
        type: string
      openapi:
        description: "Include openapi output uploaded to extra-docs-files artifact."
        required: false
        type: string

permissions:
  contents: write

jobs:
  publish_docs:
    name: Publish GH Pages
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      options: --user root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Append Extra Files
        if: ${{ inputs.doxygen || inputs.openapi }}
        uses: actions/download-artifact@v3
        with:
          name: extra-docs-files
          path: docs/

      - name: Extract Doxygen Zip
        if: ${{ inputs.doxygen }}
        run: |
          tar -xvzf docs/doxygen.tar.gz
          rm docs/doxygen.tar.gz

      - name: Publish
        run: |
          echo "Repo dir: $GITHUB_WORKSPACE"
          git config --global --add safe.directory $GITHUB_WORKSPACE
          mkdocs gh-deploy --force
