name: Publish Docs

on:
  workflow_call:
    inputs:
      image:
        description: "Override the image to build mkdocs."
        required: false
        type: string
        default: "ghcr.io/hotosm/gh-workflows/mkdocs:main"
      keep_extra_files:
        description: "Only update modified files. Default false, to clean repo before push."
        required: false
        type: boolean
        default: false
      doxygen:
        description: "Include doxygen output uploaded to extra-docs-files artifact."
        required: false
        type: string
      openapi:
        description: "Include openapi output uploaded to extra-docs-files artifact."
        required: false
        type: string
      stories:
        description: "Include story build output uploaded to extra-docs-files artifact."
        required: false
        type: string

permissions:
  contents: write

jobs:
  publish_docs:
    name: Publish GH Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Append Extra Files
        if: ${{ inputs.doxygen || inputs.openapi || inputs.stories }}
        uses: actions/download-artifact@v3
        with:
          name: extra-docs-files
          path: docs/

      - name: Extract Doxygen Zip
        if: ${{ inputs.doxygen }}
        run: |
          tar -xvzf docs/doxygen.tar.gz
          rm docs/doxygen.tar.gz

      - name: Extract Stories Zip
        if: ${{ inputs.stories }}
        run: |
          tar -xvzf docs/stories.tar.gz
          rm docs/stories.tar.gz

      - name: Publish
        run: |
          echo "Repo dir: $GITHUB_WORKSPACE"

          docker pull ${{ inputs.image }}

          docker run --volume $PWD:$PWD --workdir $PWD \
            --entrypoint=/bin/sh ${{ inputs.image }} \
            -c "\
              git config --global --add safe.directory $PWD \
              && mkdocs gh-deploy --force \
              ${{ inputs.keep_extra_files == 'true' && '--clean' || '--dirty' }}
            "
