name: Publish Docs

on:
  workflow_call:
    inputs:
      cache_path:
        required: false
        type: string
      cache_key:
        required: false
        type: string

permissions:
  contents: write

jobs:
  publish_docs:
    name: Publish GH Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Read cache
        uses: actions/cache@v3
        with:
          path: |
            .cache
            ${{ inputs.cache_path }}
          key: ${{ inputs.cache_key }}
          restore-keys: ${{ inputs.cache_key }}

      - name: Install PDM
        run: |
          python3 -m pip install pdm==2.9.3

      - name: Publish
        run: |
          pdm install -G docs --no-default
          pdm run mkdocs gh-deploy --force
