name: Build OpenAPI JSON

on:
  workflow_call:
    inputs:
      image:
        description: "The image to build to OpenAPI JSON (dependencies included, i.e. FastAPI.)."
        required: true
        type: string
      example_env_file_path:
        description: "FastAPI must start with an environment set. Path to a .env with dummy vars."
        required: true
        type: string
      output_path:
        description: "If specified, the output dir is uploaded to artifact extra-docs-files."
        required: false
        type: string

jobs:
  build_openapi_json:
    name: Build OpenAPI JSON
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      options: --user root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build OpenAPi JSON
        env:
          EXAMPLE_DOT_ENV: ${{ inputs.example_env_file_path }}
        run: |
          python - <<EOF
          """Get OpenAPI config from FastAPI and write to file."""

          import os
          import json
          from pathlib import Path

          from fastapi.openapi.utils import get_openapi
          from dotenv import load_dotenv

          load_dotenv(Path(os.getenv("EXAMPLE_DOT_ENV")))

          from app.main import api  # noqa: E402


          with open(Path("docs/openapi.json"), "w") as f:
              openapi = get_openapi(
                  title=api.title,
                  version=api.version,
                  openapi_version=api.openapi_version,
                  description=api.description,
                  routes=api.routes,
                  tags=api.openapi_tags,
                  servers=api.servers,
                  terms_of_service=api.terms_of_service,
                  contact=api.contact,
                  license_info=api.license_info,
              )
              json.dump(openapi, f, separators=(",", ":"))
          EOF

      - name: Upload Artifact Dir
        if: ${{ inputs.output_path }}
        uses: actions/upload-artifact@v3
        with:
          name: extra-docs-files
          path: ${{ inputs.output_path }}
