name: Publish to PyPi.org

on:
  workflow_call:
    inputs:
      token_secret_name:
        description: "The name of the repository secret containing the PyPi token."
        required: true
        type: string

jobs:
  publish_to_pypi:
    name: Publish to PyPi
    runs-on: ubuntu-latest
    env:
      PYPI_TOKEN: ${{ secrets[inputs.token_secret_name] }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install PDM
        run: |
          python3 -m pip install pdm==2.9.3

      - name: Publish
        run: |
          pdm config repository.pypi.username "__token__"
          pdm config repository.pypi.password "$PYPI_TOKEN"
          pdm publish
