# Note: variables: SSH_HOST and SSH_USER must be set for your environment.
# Note: secrets: SSH_PRIVATE_KEY must be set for your environment.

name: Remote Deploy (Compose)

on:
  workflow_call:
    inputs:
      environment:
        description: "The Github environment to get variables from. Default repository vars."
        required: false
        type: string
      docker_compose_file:
        description: "Path to docker compose file to deploy."
        required: true
        type: string

jobs:
  remote-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Vars and Secrets to Env
        env:
          GIT_BRANCH: ${{ github.ref_name }}
          VARS_CONTEXT: ${{ toJson(vars) }}
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
        run: |
          to_envs() { jq -r "to_entries[] | \"\(.key)=\(.value)\""; }

          echo "GIT_BRANCH=${GIT_BRANCH}" >> $GITHUB_ENV
          echo "${{ env.VARS_CONTEXT }}" | to_envs >> $GITHUB_ENV
          echo "${{ env.SECRETS_CONTEXT }}" | to_envs >> $GITHUB_ENV

      - name: Create .env file
        # run: envsubst < .env.example > .env # Only use .env.example vars
        run: env > .env

      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: "${SSH_PRIVATE_KEY}"

      - name: Add host keys to known_hosts
        run: |
          ssh-keyscan "${SSH_HOST}" >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          docker compose --file ${{ inputs.docker_compose_file }} pull
          docker compose --file ${{ inputs.docker_compose_file }} up --detach --remove-orphans
        env:
          DOCKER_HOST: ssh://"${SSH_USER}"@"${SSH_HOST}"
