# A generic workflow to run tests within a docker compose stack

name: Run Tests

on:
  workflow_call:
    inputs:
      image_name:
        description: "The image root name, without tag. E.g. 'ghcr.io/[dollar]{{ github.repository }}'"
        required: true
        type: string
      build_context:
        description: "Root directory to start the build from."
        required: false
        type: string
        default: "."
      build_dockerfile:
        description: "Name of dockerfile, relative to context dir."
        required: false
        type: string
        default: "Dockerfile"
      build_target:
        description: "The target to built to (default to ci stage)."
        required: false
        type: string
        default: "ci"
      extra_build_args:
        description: "Space separated list of build args to use for the image."
        required: false
        type: string
      tag_override:
        description: "An override for the build image tag. Must include tests and have test software installed"
        required: false
        type: string
      cache_image:
        description: "Cache the built image, for the next run. Default true."
        required: false
        type: boolean
        default: true
      cache_extra_imgs:
        description: "Space separated list of images to cache on each run (e.g. to avoid rate limiting)."
        required: false
        type: string
      compose_file:
        description: "The docker compose file used to run the test."
        required: false
        type: string
        default: docker-compose.yml
      # compose_entrypoint:
      #   description: "Override the default entrypoint for the compose service."
      #   required: false
      #   type: string
      compose_service:
        description: "The docker compose service to run the test against."
        required: true
        type: string
      compose_command:
        description: "The command to run within the docker compose service."
        required: true
        type: string
      coverage:
        description: "Generate a coverage HTML report (requires coverage.py installed)."
        required: false
        type: boolean
        default: false
      pre_command:
        description: "A initialisation command to run prior to the docker compose command."
        required: false
        type: string
      environment:
        description: "The environment to use for testing."
        required: false
        type: string
        default: "test"

jobs:
  check-img-cache:
    runs-on: ubuntu-latest
    if: ${{ inputs.cache_extra_imgs || inputs.cache_image }}
    environment:
      name: ${{ inputs.environment }}
    outputs:
      cache-hit: ${{ steps.image-cache.outputs.cache-hit }}
    steps:
      - id: image-cache
        uses: actions/cache@v3
        with:
          path: /tmp/images
          key: image-cache-${{ runner.os }}

  test-img-build:
    uses: hotosm/gh-workflows/.github/workflows/image_build.yml@1.4.0
    needs: [check-img-cache]
    if: ${{ needs.check-img-cache.outputs.cache-hit != 'true' }}
    with:
      context: ${{ inputs.build_context }}
      dockerfile: ${{ inputs.build_dockerfile }}
      build_target: ${{ inputs.build_target }}
      image_name: ${{ inputs.image_name }}
      # Default to auto-tag, unless override specified
      image_tags: ${{ inputs.tag_override && format('{0}:{1}', inputs.image_name, inputs.tag_override) || '' }}
      extra_build_args: ${{ inputs.extra_build_args }}
      # Build temp image for PR, no multi-arch, scan, or ghcr cache required
      scan_image: false
      scan_dockerfile: false
      cache: false

  run-tests:
    runs-on: ubuntu-latest
    needs: [test-img-build]
    # Ensure it runs, even if test-img-build does not run
    if: always()
    environment:
      name: ${{ inputs.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: image-cache
        if: ${{ inputs.cache_extra_imgs || inputs.cache_image }}
        uses: actions/cache@v3
        with:
          path: /tmp/images
          key: image-cache-${{ runner.os }}

      - name: Save Local Images
        if: ${{ (inputs.cache_extra_imgs || inputs.cache_image) && steps.image-cache.outputs.cache-hit != 'true' }}
        run: |
          # Function to pull and package Docker image
          function pull_and_package_image() {
            local image=$1
            echo "Processing image ${image}"
            docker pull "${image}"

            if [ $? -eq 0 ]; then
              img_underscores=${image//[:\/.]/_}
              echo "Packaging image ${image} to /tmp/images/${img_underscores}.tar"
              docker image save "${image}" --output "/tmp/images/${img_underscores}.tar"
            else
              echo "Failed to pull the image: ${image}"
            fi
          }

          # Make artifact dir
          mkdir -p /tmp/images

          # Cache main image build
          CACHE_ENABLED=${{ inputs.cache_image }}
          echo "Caching enabled: ${CACHE_ENABLED}"
          if [[ "${CACHE_ENABLED}" == true ]]; then
              image_name=${{ needs.test-img-build.outputs.image_name }}
              pull_and_package_image "${image_name}"

              # Export tag to env
              image_tag=${{ needs.test-img-build.outputs.image_tag }}
              echo "Setting TAG_OVERRIDE=${image_tag} in github env"
              echo "TAG_OVERRIDE=${image_tag}" >> $GITHUB_ENV
          fi

          # Cache extra images
          extra_images_array=(${{ inputs.cache_extra_imgs }})
          if [[ -n "${extra_images_array[@]}" ]]; then
              echo "Images to cache: ${extra_images_array[@]}"

              # Iterate through dependency images
              for image_name in "${extra_images_array[@]}"; do
                  pull_and_package_image "${image_name}"
              done
          fi

      - name: Load Cached Imgs
        if: ${{ (inputs.cache_extra_imgs || inputs.cache_image) && steps.image-cache.outputs.cache-hit == 'true' }}
        run: |
          # Load images
          for image_tar in /tmp/images/*; do
              docker image load --input $image_tar || true
          done

          # Set TAG_OVERRIDE if image was cached
          CACHE_ENABLED=${{ inputs.cache_image }}
          if [[ "${CACHE_ENABLED}" == true ]]; then
              echo "Getting image tag via docker"
              image=$(\
                docker image ls \
                --filter=reference='${{ inputs.image_name }}' \
                --format='{{.Tag}}'\
              )
              image_tag="${image##*:}"
              echo "Image Tag: $image_tag"
              echo "TAG_OVERRIDE=${image_tag}" >> $GITHUB_ENV
          fi

      - name: Vars and Secrets to Env
        env:
          TAG_OVERRIDE: ${{ env.TAG_OVERRIDE || 'ci-development' }}
          GIT_BRANCH: ${{ github.ref_name }}
          VARS_CONTEXT: ${{ toJson(vars) }}
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
        run: |
          # Random delimeter string for security
          delim=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)

          # Parse JSON with multiline strings, using delimeter (Github specific)
          to_envs() { jq -r "to_entries[] | \"\(.key)<<$delim\n\(.value)\n$delim\n\""; }

          # Set all vars
          echo "TAG_OVERRIDE=${TAG_OVERRIDE}" >> $GITHUB_ENV
          echo "GIT_BRANCH=${GIT_BRANCH}" >> $GITHUB_ENV

          # Set VARS_CONTEXT if not null
          if [ "${VARS_CONTEXT}" != "null" ]; then
            echo "${VARS_CONTEXT}" | to_envs >> $GITHUB_ENV
          fi

          # Set SECRETS_CONTEXT if not null
          if [ "${SECRETS_CONTEXT}" != "null" ]; then
            echo "${SECRETS_CONTEXT}" | to_envs >> $GITHUB_ENV
          fi

      - name: Create .env file
        run: |
          # Get a8m/envsubst (required for default vals syntax ${VAR:-default})
          echo "Downloading envsubst"
          curl -L https://github.com/a8m/envsubst/releases/download/v1.2.0/envsubst-`uname -s`-`uname -m` -o envsubst
          chmod +x envsubst

          # Check if .env.example exists
          if [ -f .env.example ]; then
            echo "Substituting variables from .env.example --> .env"
            ./envsubst < .env.example > .env
          else
            echo ".env.example not found, creating .env with GIT_BRANCH only"
            echo "GIT_BRANCH=${GIT_BRANCH}" > .env
          fi

          echo "GIT_BRANCH=${GIT_BRANCH}" >> .env

      - name: Run Tests
        if: ${{ github.event.inputs.coverage == 'false' }}
        run: |
          ${{ inputs.pre_command }}
          docker compose --file ${{ inputs.compose_file }} \
            run --no-TTY \
            ${{ inputs.compose_service }} ${{ inputs.compose_command }}

      - name: Run Tests With Coverage
        if: ${{ inputs.coverage == 'false' }}
        run: |
          ${{ inputs.pre_command }}
          docker compose --file ${{ inputs.compose_file }} \
            run --no-TTY --entrypoint "sh -c" \
            --volume ${{ github.workspace }}/coverage:/tmp/coverage \
            ${{ inputs.compose_service }} \
            "coverage run -m ${{ inputs.compose_command }} \
            && coverage report && coverage html \
            && coverage-badge -o coverage.svg \
            && mv htmlcov/index.html /tmp/coverage/coverage.html \
            && mv coverage.svg /tmp/coverage/coverage.svg"

      - name: Upload Coverage
        if: ${{ inputs.coverage == 'true' }}
        run: |
          # Pull content from gh-pages
          mkdir tmp_pages
          cd tmp_pages
          git init
          git config user.name svchot
          git config user.email sysadmin@hotosm.org
          git pull https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki
          cd ..

          # Sync coverage index and badge using rsync
          sudo apt-get update && sudo apt-get install -y rsync --no-install-recommends

          echo "Coverage dir contents:"
          ls ${{ github.workspace }}/coverage
          echo ""

          cp ${{ github.workspace }}/coverage/coverage.* docs/
          rsync -av --delete docs/ tmp_pages/ --exclude .git

          # Push content to gh-pages
          cd tmp_pages
          git add .
          git commit -m "docs: automated wiki update on push"
          git push -f --set-upstream https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git master
